Main svc
LapshYP/java-explore-with-me pull request #4
Opened 2023-08-18 10:50 UTC by LapshYP

Добрый день!
диплом вторая часть на проверку.

2023-08-20 17:13 UTC, z8q requested changes

2023-08-20 17:13 UTC, z8q commented on docker-compose.yml
>      depends_on:
container_name еще для всех можно указать, чтобы в логах чуть понятнее отражались контейнеры

2023-08-20 17:13 UTC, z8q commented on ewm-service/src/main/java/ru/practicum/ewmservice/stats/ServiceEwn.java
> +    private final StatsClient client = new StatsClient(new RestTemplate());
В MainConfig создаем бины StatsClient и RestTemplate, можно было бы их использовать. В EventServiceImpl как понял они используются

2023-08-20 17:13 UTC, z8q commented on ewm-service/src/main/java/ru/practicum/ewmservice/stats/ServiceEwn.java
> +    private final StatsClient client = new StatsClient(new RestTemplate());
Как понял, ServiceEwn задействован в EventServiceImpl, но не используется. 
И еще в контроллере, 
но нужен ли прямой доступ к статистике через контроллер?

2023-08-20 17:13 UTC, z8q commented on ewm-service/src/main/java/ru/practicum/ewmservice/stats/ServiceEwn.java
> +    private final StatsClient client = new StatsClient(new RestTemplate());
Было бы еще правильно в stats-service создать интерфейс StatsClient и там же для него реализацию StatsClientImpl. Чтобы жестко не привязываться к реализации и обращаться через интерфейс.
И если нужно было бы поменять реализацию в stats-service, не пришлось в ewm-service код менять. Подставить в stats-service другую реализацию интерфейса и все

2023-08-20 17:13 UTC, z8q commented on ewm-service/src/main/java/ru/practicum/ewmservice/event/service/EventServiceImpl.java
> +        ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
ValidatorFactory имплементит AutoCloseable, значит нужно закрывать, чтобы избежать утечек памяти.
Либо через явный вызов factory.close(), либо через блок в try, так:
```
try(ValidatorFactory factory = Validation.buildDefaultValidatorFactory()) {
            Validator validator = factory.getValidator();
            Set<ConstraintViolation<Event>> violations = validator.validate(event);
            if (!violations.isEmpty()) {
                throw new ConstraintViolationException(violations);

            }
}
```

2023-08-20 17:13 UTC, z8q commented on ewm-service/src/main/java/ru/practicum/ewmservice/event/service/EventServiceImpl.java
> +    @SneakyThrows
Попробовал убрать, никакие строчки не подсветились. Возможно нет необходимости использовать.
Обычно ставим, когда в методе не хотим обрабатывать исключение

2023-08-20 17:13 UTC, z8q commented on ewm-service/src/main/java/ru/practicum/ewmservice/event/EventController.java
> +//    @GetMapping("/events")
Закомментированный код к 19-й домашке надо будет убрать)

2023-08-20 17:13 UTC, z8q commented on ewm-service/src/main/java/ru/practicum/ewmservice/event/service/EventServiceImpl.java
> +        Event event = eventRepoJpa.findById(eventId).get();
тут делаем get, но если findById не найдет события, упадем с исключением.
Можно вместо get() использовать .orElseThrow(). Значение вернется, если будет найдено. Если нет, то бросит ошибку.
Либо что-то такое)
Event notFoundEvent = new Event();
notFoundEvent.setState(CANCELED);
Event event = eventRepoJpa.findById(eventId).orElse(notFoundEvent);
чтоб ниже в if упасть с ошибкой

2023-08-20 17:13 UTC, z8q commented on ewm-service/src/main/java/ru/practicum/ewmservice/event/service/EventServiceImpl.java
> +        HttpServletRequest request = servletRequest;
Кажется, можно не создавать переменную, ниже использовать сразу servletRequest

2023-08-20 17:13 UTC, z8q commented on ewm-service/src/main/java/ru/practicum/ewmservice/event/service/EventServiceImpl.java
> +            Request request = requestEventRepoJpa.findById(requestId).get();
Тут есть обращения к базе в цикле. Стоит такого избегать. Стараться одним запросом доставать данные.
Все requestIds отправить в одном запросе, и потом уже обрабатывать `List<Request>`
И тут снова get() есть, на котором можем упасть

2023-08-20 17:13 UTC, z8q commented on ewm-service/src/main/java/ru/practicum/ewmservice/event/repository/EventCriteriaRepositoryImpl.java
> +        Predicate annotationPredicate = null;
Неиспользуемые переменные стоит убрать

2023-08-20 17:13 UTC, z8q commented on ewm-service/src/main/java/ru/practicum/ewmservice/event/repository/EventCriteriaRepositoryImpl.java
> +            return null;
В этот блок не сможем зайти, потому что добавление в predicates точно произойдет.
либо при выполнении условия в 88-й строке, либо в блоке else 96-й строке

2023-08-21 07:52 UTC, LapshYP commented on ewm-service/src/main/java/ru/practicum/ewmservice/event/service/EventServiceImpl.java
> +        ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
поменял везде где использовалась ValidatorFactory , добавил конструкцию Try-With-Resources
в RequestServiceIml добавил валидацию которой не было

2023-08-21 08:24 UTC, LapshYP commented on ewm-service/src/main/java/ru/practicum/ewmservice/event/service/EventServiceImpl.java
> +    @SneakyThrows
убрал @SneakyThrows там где не было throw

2023-08-21 08:48 UTC, LapshYP commented on ewm-service/src/main/java/ru/practicum/ewmservice/event/EventController.java
> +//    @GetMapping("/events")
убрал весь закомментированный код

2023-08-21 08:55 UTC, LapshYP commented on ewm-service/src/main/java/ru/practicum/ewmservice/event/service/EventServiceImpl.java
> +        Event event = eventRepoJpa.findById(eventId).get();
изменил get() на orElseThrow()

2023-08-21 08:57 UTC, LapshYP commented on ewm-service/src/main/java/ru/practicum/ewmservice/event/service/EventServiceImpl.java
> +        HttpServletRequest request = servletRequest;
убрал   HttpServletRequest request = servletRequest;

2023-08-21 09:25 UTC, LapshYP commented on ewm-service/src/main/java/ru/practicum/ewmservice/event/repository/EventCriteriaRepositoryImpl.java
> +        Predicate annotationPredicate = null;
убрал не используемую переменную

2023-08-21 09:34 UTC, LapshYP commented on ewm-service/src/main/java/ru/practicum/ewmservice/event/repository/EventCriteriaRepositoryImpl.java
> +            return null;
убрал этот блок

2023-08-21 10:06 UTC, LapshYP commented on ewm-service/src/main/java/ru/practicum/ewmservice/event/service/EventServiceImpl.java
> +            Request request = requestEventRepoJpa.findById(requestId).get();
убрал цикл, заменил на List<Request>

2023-08-21 10:20 UTC, LapshYP commented on docker-compose.yml
>      depends_on:
добавил container_name

2023-08-21 14:13 UTC, LapshYP commented on ewm-service/src/main/java/ru/practicum/ewmservice/stats/ServiceEwn.java
> +    private final StatsClient client = new StatsClient(new RestTemplate());
> В MainConfig создаем бины StatsClient и RestTemplate, можно было бы их использовать. В EventServiceImpl как понял они используются

заиспользовал(кажется)

2023-08-21 14:15 UTC, LapshYP commented on ewm-service/src/main/java/ru/practicum/ewmservice/stats/ServiceEwn.java
> +    private final StatsClient client = new StatsClient(new RestTemplate());
> Как понял, ServiceEwn задействован в EventServiceImpl, но не используется. И еще в контроллере, но нужен ли прямой доступ к статистике через контроллер?
ServiceEwn  и Controller - классы удалил, т.к. они использовались в первой части диплома как проверка работоспособности связей между модулями.

2023-08-21 14:15 UTC, LapshYP commented on ewm-service/src/main/java/ru/practicum/ewmservice/stats/ServiceEwn.java
> +    private final StatsClient client = new StatsClient(new RestTemplate());
> Было бы еще правильно в stats-service создать интерфейс StatsClient и там же для него реализацию StatsClientImpl. Чтобы жестко не привязываться к реализации и обращаться через интерфейс. И если нужно было бы поменять реализацию в stats-service, не пришлось в ewm-service код менять. Подставить в stats-service другую реализацию интерфейса и все

создал интерфейс StatsClient  и создал имплементацию StatsClientImpl

2023-08-21 18:34 UTC, z8q approved these changes

2023-08-22 09:20 UTC, merged