Feature comments
LapshYP/java-explore-with-me pull request #6
Opened 2023-08-23 19:39 UTC by LapshYP

Добрый день!
Диплом 3я часть.Дополнительная функциональность - комментарии на проверку.

2023-08-24 18:33 UTC, z8q requested changes

2023-08-24 18:33 UTC, z8q commented on ewm-service/src/main/java/ru/practicum/ewmservice/comment/dto/CommentUserDto.java
> +    LocalDateTime createdtime;
JsonFormat можно поставить на все поля с датами

2023-08-24 18:33 UTC, z8q commented on ewm-service/src/main/java/ru/practicum/ewmservice/comment/controler/CommentUserController.java
> +    public List<CommentAdminDto> getAdminAllComments(@PathVariable @PositiveOrZero Long eventId,
можно было бы выделить админские запросы в отдельный контроллер

2023-08-24 18:33 UTC, z8q commented on ewm-service/src/main/java/ru/practicum/ewmservice/comment/dto/CommentUserDto.java
> +    String text;
Допускаются ли null-ы в полях?
Если есть обязательные, можно через аннотации указать

2023-08-24 18:33 UTC, z8q commented on ewm-service/src/main/java/ru/practicum/ewmservice/comment/dto/CommentUserDto.java
> +    String text;
Видел валидационные аннотации на полях в сущностях. Все таки их лучше применять на дто.
Чтобы можно было еще на обращении к контроллеру возвращать исключение, если переданы некорректные данные

2023-08-25 03:40 UTC, LapshYP commented on ewm-service/src/main/java/ru/practicum/ewmservice/comment/dto/CommentUserDto.java
> +    LocalDateTime createdtime;
добавил @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss") к полям с датами

2023-08-25 03:40 UTC, LapshYP commented on ewm-service/src/main/java/ru/practicum/ewmservice/comment/controler/CommentUserController.java
> +    public List<CommentAdminDto> getAdminAllComments(@PathVariable @PositiveOrZero Long eventId,
разделил контроллер на админский и юзера

2023-08-25 03:41 UTC, LapshYP commented on ewm-service/src/main/java/ru/practicum/ewmservice/comment/dto/CommentUserDto.java
> +    String text;
> Допускаются ли null-ы в полях? Если есть обязательные, можно через аннотации указать

сделал валидацию полей в дто классе

2023-08-25 03:41 UTC, LapshYP commented on ewm-service/src/main/java/ru/practicum/ewmservice/comment/dto/CommentUserDto.java
> +    String text;
> Видел валидационные аннотации на полях в сущностях. Все таки их лучше применять на дто. Чтобы можно было еще на обращении к контроллеру возвращать исключение, если переданы некорректные данные

сделал валидацию полей в дто классе

2023-08-25 06:53 UTC, LapshYP commented on ewm-service/src/main/java/ru/practicum/ewmservice/comment/dto/CommentUserDto.java
> +    String text;
> Допускаются ли null-ы в полях? Если есть обязательные, можно через аннотации указать

в дто нуль только допускается в id при создании, в остальных случаях id эвента и сообщения должны присутствовать (добавил это в валидацию)

2023-08-26 02:52 UTC, z8q approved these changes

2023-08-27 06:11 UTC, merged